### ISSUE TITLE
Prevent swapping order of multiple buttons in CTA

### ISSUE THREAD

**Issue by adamkudrna** [visionappscz/bootstrap-ui#108]
When there are multiple buttons or item actions in `div.cta`, they should always appear in the same order.

Currently it can be fixed like this:

```less
.cta > .btn:not(only-child),
.cta > .item-action:not(only-child) {
    @media screen and (min-width: @grid-float-breakpoint) {
        float: none;
    }
}
```
